name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - principal
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - principal

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event_name.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'

    - name: Publish Blazor App
      run: dotnet publish BlazorApp1/BlazorApp1.csproj -c Release -o BlazorApp1/wwwroot

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_FLOWER_0EC04E10 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "BlazorApp1"
        api_location: ""
        output_location: "wwwroot" # Apunta directamente a la carpeta generada por el publish previo
        skip_app_build: true
